/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevLogoRouteImport } from './routes/dev/logo'
import { Route as DevTokensRouteImport } from './routes/dev/tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogoRoute = DevLogoRouteImport.update({
  id: '/dev/logo',
  path: '/dev/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTokensRoute = DevTokensRouteImport.update({
  id: '/dev/tokens',
  path: '/dev/tokens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/logo': typeof DevLogoRoute
  '/dev/tokens': typeof DevTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/logo': typeof DevLogoRoute
  '/dev/tokens': typeof DevTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/logo': typeof DevLogoRoute
  '/dev/tokens': typeof DevTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/logo' | '/dev/tokens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/logo' | '/dev/tokens'
  id: '__root__' | '/' | '/dev/logo' | '/dev/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevLogoRoute: typeof DevLogoRoute
  DevTokensRoute: typeof DevTokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/logo': {
      id: '/dev/logo'
      path: '/dev/logo'
      fullPath: '/dev/logo'
      preLoaderRoute: typeof DevLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tokens': {
      id: '/dev/tokens'
      path: '/dev/tokens'
      fullPath: '/dev/tokens'
      preLoaderRoute: typeof DevTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevLogoRoute: DevLogoRoute,
  DevTokensRoute: DevTokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
