import { describe, expect, it } from 'vitest';
import {
  COOKIES_TOO_LARGE,
  CookiesFileError,
  NETSCAPE_HEADER,
  isYoutubeOrGoogle,
  parseCookies,
  siteOf,
  summarizeCookies,
  validateCookies,
} from './cookies-file.js';

/** A made-up export: two YouTube cookies, one Google one, one session cookie elsewhere. */
const FILE = [
  '# Netscape HTTP Cookie File',
  '# This file is generated by an exporter. Do not edit.',
  '',
  '.youtube.com\tTRUE\t/\tTRUE\t1800000000\tFAKE_ONE\tnot-a-real-value-1',
  '#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1790000000\tFAKE_TWO\tnot-a-real-value-2',
  'accounts.google.com\tFALSE\t/\tTRUE\t1810000000\tFAKE_THREE\tnot-a-real-value-3',
  'www.example.co.uk\tFALSE\t/\tFALSE\t0\tSESSION\tx',
  '',
].join('\n');

const MAX = 1024 * 1024;

describe('parseCookies', () => {
  it('reads the header and the 7-field lines, HttpOnly ones included', () => {
    const parsed = parseCookies(FILE);
    expect(parsed.hasHeader).toBe(true);
    expect(parsed.cookies).toEqual([
      { domain: 'youtube.com', expires: 1800000000 },
      { domain: 'youtube.com', expires: 1790000000 },
      { domain: 'accounts.google.com', expires: 1810000000 },
      { domain: 'www.example.co.uk', expires: 0 },
    ]);
  });

  it('skips comments, blank lines and lines of the wrong shape', () => {
    const parsed = parseCookies(
      [
        'garbage',
        '.youtube.com\tTRUE\t/\tTRUE\t1800000000\tNAME', // six fields
        '.youtube.com\tMAYBE\t/\tTRUE\t1800000000\tNAME\tv', // bad flag
        '.youtube.com\tTRUE\t/\tTRUE\tsoon\tNAME\tv', // bad expiry
        '.youtube.com\tTRUE\t/\tTRUE\t1800000000\tNAME\tv\r', // CRLF is fine
      ].join('\r\n'),
    );
    expect(parsed.hasHeader).toBe(false);
    expect(parsed.cookies).toHaveLength(1);
  });

  it('accepts the older "# HTTP Cookie File" header', () => {
    expect(parseCookies('# HTTP Cookie File\n').hasHeader).toBe(true);
  });
});

describe('siteOf and isYoutubeOrGoogle', () => {
  it('reduces a domain to its site', () => {
    expect(siteOf('www.youtube.com')).toBe('youtube.com');
    expect(siteOf('accounts.google.com')).toBe('google.com');
    expect(siteOf('youtube.com')).toBe('youtube.com');
    expect(siteOf('www.google.co.uk')).toBe('google.co.uk');
  });

  it('knows YouTube and Google domains, not look-alikes', () => {
    expect(isYoutubeOrGoogle('youtube.com')).toBe(true);
    expect(isYoutubeOrGoogle('accounts.google.com')).toBe(true);
    expect(isYoutubeOrGoogle('notyoutube.com')).toBe(false);
    expect(isYoutubeOrGoogle('youtube.com.evil.net')).toBe(false);
  });
});

/** The status and message `validateCookies` throws with, or undefined when it accepts. */
const failure = (text: string, max = MAX) => {
  try {
    validateCookies(text, max);
  } catch (error) {
    if (error instanceof CookiesFileError) return { status: error.status, message: error.message };
    throw error;
  }
  return undefined;
};

describe('validateCookies', () => {
  it('accepts an export and normalises line endings', () => {
    const result = validateCookies(FILE.replace(/\n/g, '\r\n'), MAX);
    expect(result.count).toBe(4);
    expect(result.text).not.toContain('\r');
    expect(result.text.startsWith(NETSCAPE_HEADER)).toBe(true);
    expect(
      result.text.endsWith('value-3\nwww.example.co.uk\tFALSE\t/\tFALSE\t0\tSESSION\tx\n'),
    ).toBe(true);
  });

  it('accepts valid lines without a header and adds one', () => {
    const lines = '.youtube.com\tTRUE\t/\tTRUE\t1800000000\tFAKE\tv';
    const result = validateCookies(lines, MAX);
    expect(result).toEqual({ text: `${NETSCAPE_HEADER}\n${lines}\n`, count: 1 });
  });

  it('refuses something that is not a cookies file', () => {
    expect(failure('{"cookies": []}')).toEqual({
      status: 400,
      message: 'This is not a cookies file. Export it in Netscape (cookies.txt) format.',
    });
    expect(failure('')).toMatchObject({ status: 400 });
  });

  it('refuses a file without YouTube or Google cookies', () => {
    const other = '# Netscape HTTP Cookie File\n.example.com\tTRUE\t/\tTRUE\t1800000000\tA\tb\n';
    expect(failure(other)).toEqual({
      status: 400,
      message: 'This file has no YouTube or Google cookies.',
    });
    // A header alone has no cookies at all.
    expect(failure('# Netscape HTTP Cookie File\n')).toMatchObject({ status: 400 });
  });

  it('refuses a file over the limit', () => {
    expect(failure(FILE, 100)).toEqual({ status: 413, message: COOKIES_TOO_LARGE });
  });
});

describe('summarizeCookies', () => {
  it('counts, lists sites by count and finds the soonest expiry', () => {
    expect(summarizeCookies(parseCookies(FILE))).toEqual({
      cookieCount: 4,
      domains: ['youtube.com', 'example.co.uk', 'google.com'],
      expiresSoonest: new Date(1790000000 * 1000).toISOString(),
    });
  });

  it('has no expiry for session cookies only, and ignores impossible dates', () => {
    const parsed = parseCookies(
      '.youtube.com\tTRUE\t/\tTRUE\t0\tA\tb\n.youtube.com\tTRUE\t/\tTRUE\t99999999999999\tC\td\n',
    );
    expect(summarizeCookies(parsed)).toEqual({
      cookieCount: 2,
      domains: ['youtube.com'],
      expiresSoonest: null,
    });
  });

  it('keeps the top sites only', () => {
    const lines = ['a.com', 'b.com', 'c.com', 'd.com'].map(
      (domain) => `${domain}\tFALSE\t/\tFALSE\t0\tN\tv`,
    );
    expect(summarizeCookies(parseCookies(lines.join('\n')), 3).domains).toEqual([
      'a.com',
      'b.com',
      'c.com',
    ]);
  });
});
