import { z } from 'zod';
import { Matcher } from './matchers.js';
import { Library, SourceKind, SourceOptions } from './rules.js';

/*
 * The sources API: resolving a pasted YouTube link, and creating, changing and removing
 * sources. The `Source` DTO lives in `rules.ts`, the rules (matchers) in `matchers.ts`.
 *
 * Removing a source or unsubscribing never deletes media. Only revalidation (a file the
 * source's rules no longer match) and the explicit Delete in Preview do.
 */

// ---------------------------------------------------------------------------------------
// URL parsing. Pure, so the web app can pre-validate the Add input before calling the API.
// ---------------------------------------------------------------------------------------

/** What a YouTube URL points at. A video is resolved to its channel by the API. */
export const UrlKind = z.enum(['channel', 'artist', 'playlist', 'video']);
export type UrlKind = z.infer<typeof UrlKind>;

export interface ParsedYoutubeUrl {
  kind: UrlKind;
  /**
   * The identifier as it appears in the URL: a handle (`@NASA`), a channel id (`UC…`), a
   * legacy name (`c/name`, `user/name`), a playlist id, or a video id.
   */
  id: string;
  /** Canonical URL: `https`, no tracking parameters, `www.` or `music.` host. */
  url: string;
  /** The link came from YouTube Music (`music.youtube.com`). */
  music: boolean;
}

// `URL` is a global in browsers and Node, but shared compiles against the ES library only.
interface ParsedUrl {
  protocol: string;
  hostname: string;
  pathname: string;
  searchParams: { get(name: string): string | null };
}
declare const URL: new (input: string) => ParsedUrl;

const HOSTS = new Set(['youtube.com', 'www.youtube.com', 'm.youtube.com', 'music.youtube.com']);
const SHORT_HOSTS = new Set(['youtu.be', 'www.youtu.be']);
const CHANNEL_ID = /^UC[\w-]{22}$/;
const VIDEO_ID = /^[\w-]{11}$/;
const PLAYLIST_ID = /^[\w-]{10,64}$/;
const LEGACY_NAME = /^[\w.-]{1,100}$/;
const HANDLE = /^@[^\s/?#@]{1,100}$/;
/**
 * Lists that are not real playlists: `RD…` mixes are generated by the recommendation engine
 * (except `RDCLAK…`, YouTube Music's curated playlists), and `LL` (liked videos), `WL` (watch
 * later) and `LM` (liked music) need an account. A `watch?v=…&list=RD…` link is treated as
 * the video alone.
 */
const PRIVATE_OR_GENERATED_LIST = /^(RD(?!CLAK)|LL$|WL$|LM$)/;

/**
 * Recognises the YouTube links MyTube can add and returns what they point at with a
 * canonical URL, or null for anything else:
 *
 * - `youtube.com/@handle`, `/channel/UC…`, `/c/name`, `/user/name` (any sub-page) → channel
 * - `music.youtube.com/channel/UC…` → artist
 * - `/playlist?list=…` and `watch?v=…&list=…` (on either host) → playlist
 * - `watch?v=…`, `youtu.be/…`, `/shorts/…`, `/live/…` → video (the API resolves its channel)
 * - a bare handle (`@NASA`) → channel
 *
 * Scheme is optional; `m.` hosts are accepted. Mixes, liked and watch-later lists are not.
 */
export function parseYoutubeUrl(input: string): ParsedYoutubeUrl | null {
  const text = input.trim();
  if (!text || /\s/.test(text)) return null;
  if (HANDLE.test(text)) return channel(text, false);

  let url: ParsedUrl;
  try {
    url = new URL(/^[a-z][a-z\d+.-]*:\/\//i.test(text) ? text : `https://${text}`);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:' && url.protocol !== 'http:') return null;
  const host = url.hostname.toLowerCase();
  const segments = url.pathname
    .split('/')
    .filter(Boolean)
    .map((segment) => safeDecode(segment));
  const list = url.searchParams.get('list');

  if (SHORT_HOSTS.has(host)) {
    const videoId = segments[0];
    if (!videoId || !VIDEO_ID.test(videoId)) return null;
    return playlistOrVideo(list, videoId, false);
  }
  if (!HOSTS.has(host)) return null;
  const music = host === 'music.youtube.com';
  const [first, second] = segments;
  if (!first) return null;

  if (first.startsWith('@')) return HANDLE.test(first) ? channel(first, music) : null;
  if (first === 'channel') {
    if (!second || !CHANNEL_ID.test(second)) return null;
    return music
      ? { kind: 'artist', id: second, url: `https://music.youtube.com/channel/${second}`, music }
      : channel(second, music);
  }
  if (first === 'c' || first === 'user') {
    if (music || !second || !LEGACY_NAME.test(second)) return null;
    const id = `${first}/${second}`;
    return { kind: 'channel', id, url: `https://www.youtube.com/${id}`, music };
  }
  if (first === 'playlist' && segments.length === 1) {
    return list && isAddableList(list) ? playlist(list, music) : null;
  }
  if (first === 'watch' && segments.length === 1) {
    const videoId = url.searchParams.get('v');
    if (!videoId || !VIDEO_ID.test(videoId)) return null;
    return playlistOrVideo(list, videoId, music);
  }
  if ((first === 'shorts' || first === 'live' || first === 'embed') && second) {
    return VIDEO_ID.test(second) ? video(second, music) : null;
  }
  return null;
}

/** The library a parsed link most likely belongs to: Music for YouTube Music links. */
export function guessLibrary(parsed: Pick<ParsedYoutubeUrl, 'music'>): Library {
  return parsed.music ? 'music' : 'video';
}

function channel(id: string, music: boolean): ParsedYoutubeUrl {
  // A handle or channel id on music.youtube.com only exists as `/channel/UC…` (an artist);
  // handles always live on www.
  return {
    kind: 'channel',
    id,
    url: `https://www.youtube.com/${id.startsWith('@') ? id : `channel/${id}`}`,
    music,
  };
}

function playlist(id: string, music: boolean): ParsedYoutubeUrl {
  const host = music ? 'music.youtube.com' : 'www.youtube.com';
  return { kind: 'playlist', id, url: `https://${host}/playlist?list=${id}`, music };
}

function video(id: string, music: boolean): ParsedYoutubeUrl {
  const host = music ? 'music.youtube.com' : 'www.youtube.com';
  return { kind: 'video', id, url: `https://${host}/watch?v=${id}`, music };
}

function playlistOrVideo(list: string | null, videoId: string, music: boolean) {
  return list && isAddableList(list) ? playlist(list, music) : video(videoId, music);
}

function isAddableList(list: string): boolean {
  return PLAYLIST_ID.test(list) && !PRIVATE_OR_GENERATED_LIST.test(list);
}

function safeDecode(segment: string): string {
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
}

// ---------------------------------------------------------------------------------------
// Upload cadence.
// ---------------------------------------------------------------------------------------

const DAY_MS = 86_400_000;

/**
 * Uploads per week from the publish times (ms since epoch, any order) of a source's newest
 * items: `(count − 1)` intervals over the span between the oldest and newest, rounded to one
 * decimal. The span is at least one day, because flat channel listings only date items to
 * the day. null with fewer than two dated items.
 */
export function uploadsPerWeek(times: readonly number[]): number | null {
  const valid = times.filter((time) => Number.isFinite(time));
  if (valid.length < 2) return null;
  const span = Math.max(Math.max(...valid) - Math.min(...valid), DAY_MS);
  return Math.round(((valid.length - 1) / (span / DAY_MS / 7)) * 10) / 10;
}

// ---------------------------------------------------------------------------------------
// DTOs.
// ---------------------------------------------------------------------------------------

/** `POST /api/sources/resolve` body. */
export const ResolveRequest = z.strictObject({
  url: z.string().trim().min(1).max(2000),
});
export type ResolveRequest = z.infer<typeof ResolveRequest>;

/** `POST /api/sources/resolve` response: what the Add modal's source card shows. */
export const ResolvedSource = z.object({
  /** The source kind for `library`: a YouTube Music link resolves to an artist. */
  kind: SourceKind,
  /** The guessed library: Music for music.youtube.com links, else Video. */
  library: Library,
  /** Channel id (`UC…`) or playlist id. What the source row's `youtubeId` will be. */
  youtubeId: z.string().min(1),
  /** Canonical, id-based URL (`/channel/UC…`, `/playlist?list=…`). */
  url: z.url(),
  name: z.string().min(1),
  avatarUrl: z.url().nullable(),
  /**
   * Total items YouTube reports. Known for playlists; null for channels and artists, whose
   * flat listings carry no total.
   */
  itemCount: z.number().int().nonnegative().nullable(),
  /** From the newest items' dates; null with fewer than two dated items (playlists). */
  uploadsPerWeek: z.number().nonnegative().nullable(),
  /** Publish time of the newest dated item, null when none is dated. */
  latestItemAt: z.iso.datetime().nullable(),
  /** Set when the link was a single video and the source is its channel. */
  resolvedFrom: z.literal('video').nullable(),
  /**
   * The existing source with this YouTube id: the one in the guessed library, else the one in
   * the other library. null when it has not been added.
   */
  alreadyAdded: z.object({ sourceId: z.number().int().positive(), library: Library }).nullable(),
});
export type ResolvedSource = z.infer<typeof ResolvedSource>;

/**
 * Option inputs: every field optional (no defaults) so the API can tell which ones the client
 * set. On create they overlay the defaults (`music.embedCoverArt` from Settings for music), on
 * update the source's current options. Unknown fields are rejected.
 */
export const SourceOptionsInput = z.strictObject({
  embedCoverArt: SourceOptions.shape.embedCoverArt.unwrap().optional(),
  syncOrder: SourceOptions.shape.syncOrder.unwrap().optional(),
});
export type SourceOptionsInput = z.infer<typeof SourceOptionsInput>;

export const SOURCE_NAME_MAX = 200;

/**
 * `POST /api/sources` body. The API resolves `url` again (nothing is cached). `kind` defaults
 * to the resolved kind, mapped to the library: a channel saved to Music becomes an artist and
 * an artist saved to Video a channel. A playlist stays a playlist.
 */
export const CreateSource = z.strictObject({
  url: z.string().trim().min(1).max(2000),
  library: Library,
  kind: SourceKind.optional(),
  /** The rules; the library's default tree from Settings when omitted. */
  matcher: Matcher.optional(),
  options: SourceOptionsInput.optional(),
});
export type CreateSource = z.infer<typeof CreateSource>;

/**
 * `PATCH /api/sources/:id` body. At least one field. `matcher` replaces the rules as a whole
 * (and queues a revalidation); `options` overlay the current options.
 */
export const UpdateSource = z
  .strictObject({
    matcher: Matcher.optional(),
    options: SourceOptionsInput.optional(),
    subscribed: z.boolean().optional(),
    name: z.string().trim().min(1).max(SOURCE_NAME_MAX).optional(),
  })
  .refine((body) => Object.values(body).some((value) => value !== undefined), {
    message: 'Nothing to update',
  });
export type UpdateSource = z.infer<typeof UpdateSource>;

/** `PATCH /api/sources/:id/subscribed` body: the bell. */
export const SetSubscribed = z.strictObject({ subscribed: z.boolean() });
export type SetSubscribed = z.infer<typeof SetSubscribed>;

/** `GET /api/sources` query. Other parameters are ignored. */
export const ListSourcesQuery = z.object({ library: Library.optional() });
export type ListSourcesQuery = z.infer<typeof ListSourcesQuery>;

/** Body of the 409 from `POST /api/sources` when the source already exists in that library. */
export const SourceConflict = z.object({
  statusCode: z.literal(409),
  message: z.string(),
  sourceId: z.number().int().positive(),
});
export type SourceConflict = z.infer<typeof SourceConflict>;

/** `POST /api/sources/:id/rules/preview` body: the rules the Edit modal is about to save. */
export const RulesPreviewRequest = z.strictObject({ matcher: Matcher });
export type RulesPreviewRequest = z.infer<typeof RulesPreviewRequest>;

/**
 * `POST /api/sources/:id/rules/preview` response: the files on disk the candidate rules would
 * remove (`id` is the video or track id), and how many on-disk files they keep.
 */
export const RulesPreview = z.object({
  wouldRemove: z.array(
    z.object({
      id: z.number().int().positive(),
      title: z.string(),
      /** The conditions the item fails (`not older than 90 days`). */
      failing: z.array(z.string()),
    }),
  ),
  wouldKeep: z.number().int().nonnegative(),
});
export type RulesPreview = z.infer<typeof RulesPreview>;
